### PR TITLE
Fix incorrect name for city New London [id:4839416].

### PR DESCRIPTION
**Pull request by Crozzers**
In the old `cities.db.bz2` file the record for "New London" [id: 4839416] had the name set incorrectly to `"New Londonhttps://www.geonames.org/1524325/ekibastuz.html#"`, as seen in this screenshot:

image

In the updated `cities.db.bz2` file this has been corrected as shown here:

image

### CODE REVIEW

**Comment by Crozzers** [comment]
Upon further investigation, it appears that the file that the sqlite database is generated from contains the error. However, since this file is hosted on OpenWeatherMap's servers (http://bulk.openweathermap.org/sample/city.list.json.gz) I am not sure how to fix that.

I have reported this issue via their [Ask a question](https://home.openweathermap.org/questions) portal

**Comment by csparpa** [comment]
@Crozzers good catch, thanks! 
I use an automated script to generate CityID files from the JSON file coming from OWM website... this one: https://github.com/csparpa/pyowm/blob/develop/scripts/generate_city_id_files.py

If you manage to regenerate the SQLite DB, that would be great! 
Otherwise please tell me and I'll do it as soon as I have time

Thanks so much

**Comment by Crozzers** [comment]
When I made the commit all I did was edit the database itself as I wasn't yet aware that it was auto-generated.

I could tweak the generator to detect URLs in words/invalid words and ask the user for a correction if you think that makes sense

**Comment by csparpa** [comment]
It definitely does!
You would be able to detect URLs in words but probably not much else - but
that's a starting point

Thanks!

Claudio

**Comment by Crozzers** [comment]
I'll start working on that then.

**Comment by Crozzers** [comment]
I've added the checks for whether an entry contains a URL. It will check each city name, country and state for URLs and suggest a correction if one is found. The user can then either accept or  deny the suggestion or manually enter a correction themselves.

I also attempted to enable testing with Python 3.10 but that failed with the following error
`AttributeError: 'dict' object has no attribute 'select'`

**Comment by Crozzers** [comment]
Quick update, I mentioned previously:

> Upon further investigation, it appears that the file that the sqlite database is generated from contains the error. However, since this file is hosted on OpenWeatherMap's servers (http://bulk.openweathermap.org/sample/city.list.json.gz) I am not sure how to fix that.
> I have reported this issue via their [Ask a question](https://home.openweathermap.org/questions) portal

I did receive an email response saying that the developer team has been notified of the error.
Hopefully this means that it will be fixed at some point in the not too distant future but as of the time of writing, it has not.

**Comment by csparpa** [comment]
Thank you so much @Crozzers for the update, I'll check on your PR as soon as possible

**Pull request merged**
