### PR TITLE
Updated OneCall API to v3.0

### PR DESCRIPTION
**Pull request by JakeThomson**
OpenWeatherMap deprecated their OneCall v2.5 endpoint (https://github.com/csparpa/pyowm/issues/404), upgrading to use v3.0 instead.

### CODE REVIEW

**Comment by kmcnellis** [comment]
+1

**Comment by csparpa** [comment]
Hi I'm not able to test the PR locally, I trust you @JakeThomson have done it and PyOWM is now working again with the free tier API keys

**Comment by csparpa** [comment]
Also @JakeThomson thanks for this

You've patched the master branch, pls merge your changes also on the development branch if you have the possibility 
Thanks again!

**Comment by JakeThomson** [comment]
> Also @JakeThomson thanks for this
> 
> You've patched the master branch, pls merge your changes also on the development branch if you have the possibility Thanks again!

No problem, I had a look at this but it seems your master/develop branches are out of sync with each other and there are conflicts that I do not have the time to look into I am afraid.

@csparpa I was however wondering if we would be able to see a release for this change? I am having issues with my CI by pointing to the specific commit in my requirements.txt

**Comment by kevincrane** [comment]
Any thoughts on a new release for this library? The OWM 2.5 API officially died a few weeks back and the latest 3.3.0 library that `pip` pulls in doesn't have the updated 3.0 URLs included. Thanks!

**Pull request merged**
