### PR TITLE
Dockerfiles and build utils for Alpine containers

### PR DESCRIPTION
**Pull request by Simone-Zabberoni**
Hi, I've added the dockerfiles for Alpine linux, a build script and a small python example to check them.

The 2 small images are ok.
Please check the "dev" one: I've added every package I found to match the ubuntu version but it's still a different platform

Current image size:
csparpa/pyowm.alpine-py2small       latest              75809058cd77        11 minutes ago      81.88 MB
csparpa/pyowm.alpine-py3small       latest              095eabc2ff69        17 minutes ago      127.8 MB
csparpa/pyowm.alpine-dev            latest              e10e00787e77        17 minutes ago      328.6 MB

S.

### CODE REVIEW

**Comment by csparpa** [comment]
Thanks @Simone-Zabberoni !

This actually aims to fix #204 

Unfortunately, I've noticed that the Travis CI integration of your Pull Request broke. Can you please fix it?

**Comment by csparpa** [comment]
Also @Simone-Zabberoni I would ask you if you could open the same PR on the `develop` branch instead of the `master` branch

The latter is intended for production use only

Thank you very much!

**Comment by Simone-Zabberoni** [comment]
Ok, I'll update the PR on `delevop`.

The CI integration failed on all pyenv but 3.5 with the same error:

```
pyenv: python3.5: command not found

The `python3.5' command exists in these Python versions:
  3.5
  3.5.3
```
even if I did not touch the code, seems to be an issue between Tox and Travis.


I found something [here](https://github.com/pytest-dev/pytest/issues/2779), the suggestion is to switch to [tox-travis](https://pypi.python.org/pypi/tox-travis). 
Unfortunately I'm not too skilled on travis yet, but I'll give it a try!

**Comment by csparpa** [comment]
Grazie!! Good job!

**Pull request closed without merging**
